"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.parseCSVFile = exports.decompressAndExtract = exports.downloadFile = exports.batchInsertData = exports.createTable = void 0;
var createTable_1 = require("./createTable");
Object.defineProperty(exports, "createTable", { enumerable: true, get: function () { return createTable_1.createTable; } });
var batchInsertData_1 = require("./batchInsertData");
Object.defineProperty(exports, "batchInsertData", { enumerable: true, get: function () { return batchInsertData_1.batchInsertData; } });
var downloadFile_1 = require("./downloadFile");
Object.defineProperty(exports, "downloadFile", { enumerable: true, get: function () { return downloadFile_1.downloadFile; } });
var decompressAndExtract_1 = require("./decompressAndExtract");
Object.defineProperty(exports, "decompressAndExtract", { enumerable: true, get: function () { return decompressAndExtract_1.decompressAndExtract; } });
var parseCSVFile_1 = require("./parseCSVFile");
Object.defineProperty(exports, "parseCSVFile", { enumerable: true, get: function () { return parseCSVFile_1.parseCSVFile; } });
